### ISSUE TITLE
Export Word - La vignette est mal positionnée et le logo Isogeo trop grand

### ISSUE THREAD

**Issue by leodarengosse** [isogeo/export-docx-py#1]
## Reproduire

1. Lancer l'application isogeo2office.exe
2. Vérifier que la table de correspondance est vide et que le modèle Word n'a pas été modifié
3. Exporter un catalogue en word
4. La vignette empiète sur le résumé et le logo d'Isogeo est trop grand (cf. fichier joint)

[metadonneesdonnees_libres_arbre_rem_newversion.docx](https://github.com/isogeo/isogeo-2-office/files/3165549/metadonneesdonnees_libres_arbre_rem_newversion.docx)

**Comment by Guts** [comment]
Il s'agit juste d'une mauvaise compréhension du fonctionnement décrit ici : http://help.isogeo.com/isogeo2office/fr/export/word/thumbnails.html

**Vignette**

A l'instar des autres champs, c'est l'utilisateur final qui est chargé d'organiser son modèle d'export comme il le souhaite, en l'occurrence via la variable `varThumbnail`.

**Logo**

Comme dit dans la doc, le logo Isogeo est inséré si la variable de remplacement `varThumbnail`est présente mais qu'aucune image n'est transmise.
