### ISSUE TITLE
Export Word : quelques champs ne sont pas récupérés correctement

### ISSUE THREAD

**Issue by leodarengosse** [isogeo/export-docx-py#2]
## Reproduire

1. Lancer l'application isogeo2office.exe
2. Exporter un catalogue en Word

**Exemple pour la fiche Arbres remarquables de l'AEV**
https://app.isogeo.com/groups/c18ddc43d1c045fc85c2ba1b4233eef1/resources/2906680962424c5aa2555fc8b2a33faf/identification

Au regard du fichier word _metadonneesdonnees_libres_arbre_rem_newversion.docx_ obtenu en PJ, on constate : 

* Les conditions de diffusion ne sont pas récupérées ;
* Le lien vers l'OpenCatalog n'est pas le bon ;
* Les ressources ne sont pas récupérées (lien vers le site arbres.org par exemple).

[metadonneesdonnees_libres_arbre_rem_newversion.docx](https://github.com/isogeo/isogeo-2-office/files/3165370/metadonneesdonnees_libres_arbre_rem_newversion.docx)

**Comment by Guts** [comment]
Ce ticket est trop vague. Il nécessite d'être "explosé" en plusieurs tickets sur chaque sujet spécifique.
